# Generated by Django 5.1 on 2024-11-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact Us Messages'},
        ),
    ]
